lint.select = ["ALL"]
lint.ignore = ["FA", "D100", "G004", "ANN101", "ANN102"]
line-length = 100
lint.unfixable = ["F401"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"tests/*.py" = ["S101"]